### ISSUE TITLE
“python_requires” should be set with “>=3.6”, as pytest-console-scripts 1.2.2 is not compatible with all Python versions.

### ISSUE THREAD

**Issue by PyVCEchecker** [kvas-it/pytest-console-scripts#51]
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found it is not compatible with **Python 2**. My local Python version is 2.7, and I encounter the following error when executing _“pip install pytest-console-scripts”_ 

```
Collecting pytest-console-scripts
  Downloading pytest-console-scripts-1.2.2.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rXjTtr/pytest-console-scripts/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rXjTtr/pytest-console-scripts/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rXjTtr/pytest-console-scripts/pip-egg-info
         cwd: /tmp/pip-install-rXjTtr/pytest-console-scripts/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rXjTtr/pytest-console-scripts/setup.py", line 21, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-install-rXjTtr/pytest-console-scripts/setup.py", line 7, in read
        with open(file_path, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I found that **setup.py** used a Python3-specific keyword argument **encoding** for the function **open**, which lead to installation failure of Inject in Python 2. I also noticed that the project is dropping support for Python 3.5, so I think it better to set **python_requires** with ">=3.6" rather than ">=3".

Way to fix:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires=">=3.6"
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by kvas-it** [comment]
Yes, this makes sense. Thank you.
