### ISSUE TITLE
1.3.1: missing install-time dependencies

### ISSUE THREAD

**Issue by kloczek** [kvas-it/pytest-console-scripts#56]
During `pep440` test suite execution I found that pytest failed because missing `pkg_resources` module in build env.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pep440-0.1.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pep440-0.1.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
Traceback (most recent call last):
  File "/usr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1017, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1305, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1188, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/usr/lib/python3.8/site-packages/pytest_console_scripts.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
And indeed in https://github.com/kvas-it/pytest-console-scripts/blob/a34120fae03022100bfd3ea1968fd55600ddca27/pytest_console_scripts.py#L6
is import of that module and in
https://github.com/kvas-it/pytest-console-scripts/blob/a34120fae03022100bfd3ea1968fd55600ddca27/setup.py#L24
is missing that install time dependency.

Quirck solution could be patch like below
```patch
--- a/setup.py
+++ b/setup.py
@@ -21,7 +21,7 @@
     long_description=read('README.md'),
     long_description_content_type='text/markdown',
     py_modules=['pytest_console_scripts'],
-    install_requires=['pytest>=4.0.0'],
+    install_requires=['pytest>=4.0.0', 'pkg_resources'],
     python_requires='>=3.6',
     setup_requires=['setuptools-scm'],
     classifiers=[
```
however basing on https://github.com/pypa/setuptools/issues/3279 better would be migrate to use `importlib_metadata` like https://git.smhi.se/climix/climix/-/merge_requests/165.patch

**Comment by kloczek** [comment]
That quick patch is incorect. `pkg_resources` is part of the `seuptools` however `pkg_resources` does not porvude any metadata for `pkg_resources` so correct quick patch shoud be
```patch
--- a/setup.py
+++ b/setup.py
@@ -21,7 +21,7 @@
     long_description=read('README.md'),
     long_description_content_type='text/markdown',
     py_modules=['pytest_console_scripts'],
-    install_requires=['pytest>=4.0.0'],
+    install_requires=['pytest>=4.0.0', 'setuptools],
     python_requires='>=3.6',
     setup_requires=['setuptools-scm'],
     classifiers=[
```

**Comment by frenzymadness** [comment]
It'd be nice to fix that. Would a PR speed this up?

**Comment by kloczek** [comment]
Any plans to rel;ease new version? 🤔

**Comment by HexDecimal** [comment]
I'd like to make a new release after #69 is merged.

**Comment by kloczek** [comment]
Thx 👍
